import Head from "next/head";
import { resetServerContext } from "react-beautiful-dnd";
import Todos from "../components/Todos";

export default function Home() {
  return (
    <div className="h-screen w-screen overflow-x-hidden">
      <Head>
        <title>To-do-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute top-0 right-0 left-0 w-full sm:h-[45%] h-[30%] bg-light-img-mobile bg-cover sm:bg-light-img-desktop dark:bg-dark-img-mobile dark:sm:bg-dark-img-desktop z-[-1]" />
      <div className="flex justify-center">
        <Todos />
      </div>
    </div>
  );
}

export async function getServerSideProps({ query }) {
  resetServerContext();

  return { props: { data: [] } };
}
